site_name: Pinterest
extra_css: [extra.css]
pages:
  - Home: index.md
  - Pré-rastreabilidade:
    - Argumentação: argumentacao.md
    - RichPicture: rich_picture.md
  - Elicitação de Requisitos:
    - Análise de Discurso: analise_discurso.md
    - Análise de Protocolo: analise_protocolo.md
    - Entrevista: entrevista.md
    - Introspecção: introspeccao.md
    - Questionário: questionario.md
    - Storytelling: storytelling.md
    - Conclusão: conclusao_elicitacao.md
  - Modelagem:
    - Cenários: cenarios.md
    - Léxicos: lexicos.md
    - Diagramas de Caso de Uso: diagramas_caso_uso.md
    - Especificações de Caso de Uso: especificacoes_caso_uso.md
    - Backlog do Produto: backlog.md
    - NFR: nfr.md

theme: readthedocs
