site_name: Pinterest
extra_css: [extra.css]
pages:
  - Home: index.md
  - Pré-rastreabilidade:
    - Argumentação: argumentacao.md
    - RichPicture: rich_picture.md
  - Elicitação de Requisitos:
    - Análise de Protocolo: analise_protocolo.md
    - Questionário: questionario.md
    - Introspecção: introspeccao.md
    - Storytelling: storytelling.md
    - Entrevista: entrevista.md
    - Conclusão: conclusao_elicitacao.md
  - Anexos: anexos.md
theme: readthedocs
